### ISSUE TITLE
Early choreography start

### ISSUE THREAD

**Issue by cyri113** [TogetherCrew/api#103]
server-comm is creating + starting the DISCORD_UPDATE_CHANNELS choreography before we have finished configuring it. 

This results in discord-bot, discord-analyzer-server and discord-analyzer-worker running their processes without data.

while this doesn't break anything, it isn't pretty or efficient.

**Comment by scientiststwin** [comment]
@cyri113 what do you mean by "before configuring it"? 

Do you mean we publish the message before saving data in DB? Or something else?
Could you please explain clearly?
