### ISSUE TITLE
Announcement Username

### ISSUE THREAD

**Issue by scientiststwin** [TogetherCrew/api#291]
It doesn't work correctly when we want to send a message to users with their **username** in the text.

### Current behaviour:
**input:** 
`text`: ``Hey {{username}}``
`keys`: ``{ username: "twin" }``
**output**: 
_Hey @23423423_

### Expected behaviour: 
**input:** 
`text`: ``Hey {{username}}``
`keys`: ``{ username: "twin" }``
**output:** 
_Hey @twin_

**Comment by scientiststwin** [comment]
It was fixed with the input data that should pass ```{{{username}}}``` instead of ```{{username}}```

**Comment by TwiN** [comment]
Hi @scientiststwin :)
